name: fengwuxp_openfeign_boot
description: openfeign dart  boot
version: 0.0.3
author: fengwuxp
homepage: https://github.com/fengwuxp/dart_openfeign

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reflectable: '>=2.0.0'

  logging: ^0.11.4
  fengwuxp_dart_basic:
    git: git://github.com/fengwuxp/fengwuxp_dart_basic.git
#  fengwuxp_dart_openfeign:
#    git:
#      url: git://github.com/fengwuxp/fengwuxp_dart_feign.git
#      ref: feature/annotation_changes
  fengwuxp_dart_openfeign:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  quiver: '>=0.21.0 <3.0.0'
  test: ^1.0.0
  build_runner: any
  build_test: any
  # If you need to run web tests, you will also need this dependency.
  #  build_web_compilers: any
  built_value_generator: '>7.0.0'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
